### ISSUE TITLE
Centos UEFI not overwritten

### ISSUE THREAD

**Issue by ajd394** [fcaviggia/hardened-centos7-kickstart#11]
When i boot in BIOS mode i see the Hardened install menu but booting in UEFI mode displays the regular Centos 7 install menu.

**Comment by ajd394** [comment]
someone having a similar problem (no solution discussed ) https://www.centos.org/forums/viewtopic.php?t=48639

**Comment by symgryph** [comment]
This seems to have been fixed. You DO have to run the installer from its default directory, however. Seems like running it outside of that (I just created a script that 'cd's' to the directory. Otherwise seems likes it doesn't work.

**Comment by ajd394** [comment]
@symgryph Hey I'm having trouble understanding how you are able to make it work. I cloned this repo and executed createiso.sh after "cd hardened-centos7-kickstart".  then dd the hardened iso to a usb and booted to it in UEFI mode. at that point i saw the regular Centos 7 install menu.

**Comment by fcaviggia** [comment]
Have you tried recently? I believe this issue has been fixed.

**Comment by fcaviggia** [comment]
Okay, I'll do some testing - but I'm going to close this issue for now.

**Comment by symgryph** [comment]
You probably need to set the bios to emulate a cd 💿.

Thomas J Munn

**Comment by ajd394** [comment]
I also found that virtualbox doesn't see the hardened boot menu but VMware fusion does. Basically the type of bios makes a big difference. I see this as an issue still.

**Comment by fcaviggia** [comment]
I can check virtualbox here in a bit - I've only tested it in KVM and
VMware.

-Frank

**Comment by ajd394** [comment]
@fcaviggia in the virtualbox settings i tried checking the EFI mode to no avail.

**Comment by fcaviggia** [comment]
Latest version - looks good to me - CentOS 7.3 (1611) booting with UEFI on
VirtualBox v5.1.22 - only configuration item was selection EFI in the
System Menu - Installed just fine. I've also tested with KVM (on Fedora 25)
and VMware ESXi 6.5


​
